kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ${{ values.repoName }}-route
  labels:
    app: ${{ values.repoName }}
    app.kubernetes.io/component: ${{ values.repoName }}
    app.kubernetes.io/instance: ${{ values.repoName }}
  annotations:
    openshift.io/host.generated: 'true'
    argocd.argoproj.io/sync-wave: "7"
spec:
  to:
    kind: Service
    name: ${{ values.repoName }}
    weight: 100
  port:
    targetPort: http-${{ values.port }}
  wildcardPolicy: None