kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${{ values.repoName }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  labels:
    backstage.io/kubernetes-id: ${{ values.repoName }}
    app: ${{ values.repoName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.repoName }}
  template:
    metadata:
      labels:
        app: ${{ values.repoName }}
        app.kubernetes.io/component: backstage
        backstage.io/kubernetes-id: ${{ values.repoName }}
    spec:
      containers:
        - name: ${{ values.repoName }}
          image: ${{ values.imageRepository }}/${{ values.imageUrl }}
          ports:
            - name: http-${{ values.port }}
              containerPort: ${{ values.port }}
              protocol: TCP
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: postgresql
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: postgresql
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: postgresql