apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ${{ values.repoName }}-el
  namespace: ${{ values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: gitlab-push
      interceptors:
        - params:
            - name: eventTypes
              value: ['push']
          ref:
            name: gitlab
        - params:
            - name: git-revision
              value: >-
                (body.ref.contains('main'))
            - name: overlays
              value: null
          ref:
            name: cel
      template:
        ref: ${{ values.repoName }}-run-pipeline