apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ${{ values.repoName }}-pipeline-run-init
  namespace: ${{ values.namespace }}
  labels:
    tekton.dev/pipeline: ${{ values.repoName }}-pipeline
    backstage.io/kubernetes-id: ${{ values.repoName }}
    type: pipeline
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  params:
    - name: source-repo
      value: 'https://${{ values.host }}/${{ values.orgName }}/${{ values.repoName }}.git'
    - name: source-branch
      value: main
    - name: output-image
      value: ${{ values.imageRepository }}/${{ values.imageUrl }}
  pipelineRef:
    name: ${{ values.repoName }}-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi