{%- if values.componentName %}
  {%- set name = values.componentName %}
{%- else %}
  {%- set name = values.repoName %}
{% endif -%}

apiVersion: backstage.io/v1alpha1
  {%- if values.entityKind %}
kind: ${{ values.entityKind }}
  {%- else %}
kind: Component
  {%- endif %}
metadata:
  name: ${{ name }}
  {%- if values.title %}
  title: ${{ values.title }}
  {%- endif %}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
    {%- if values.host %}
    argocd/app-name: ${{ name }}
    {%- endif %}
    {%- if values.ci == "../../skeletons/ci/tekton/" %}
    janus-idp.io/tekton: ${{ name }}
    tektonci/build-namespace: ${{ values.namespace }}
    {%- endif %}
    backstage.io/kubernetes-id: ${{ name }}
    backstage.io/source-location: url:https://${{values.host}}/${{values.destination}}
    backstage.io/techdocs-ref: dir:.
    {%- if values.sourceControl == "gitlab.com" %}
    gitlab.com/project-slug: ${{values.destination}}
    {%- elif values.sourceControl == "github.com" %}
    github.com/project-slug: ${{values.destination}}
    {%- endif %}
  tags:
    - java
    - spring-boot
  links:
    - url: https://devspaces${{values.cluster}}/#https://${{values.host}}/${{values.destination}}
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces${{values.cluster}}/#https://${{values.host}}/${{values.destination}}?che-editor=che-incubator/che-idea/latest
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: ${{ values.applicationType }}
  {%- if values.system %}
  system: ${{ values.system }}
  {%- endif %}
  {%- if values.lifecycle %}
  lifecycle: ${{ values.lifecycle }}
  {%- else %}
  lifecycle: production
  {%- endif %}
  owner: ${{ values.owner }}
  {%- if values.dependsOn %}
  dependsOn:
    - ${{ values.dependsOn }}
  {%- endif %}
  {%- if values.partOf %}
  partOf:
    - ${{ values.partOf }}
  {%- endif %}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.repoName | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
spec:
  type: openapi
  lifecycle: production
  owner: ${{values.owner | dump}}
  definition:
    $text: ./openapi.yaml
